import type { Metadata } from 'next'
import '../styles/globals.css'
import { GlobalProvider } from '@/api/provider/global.provider'
import { plusJakartaFont } from '@/assets/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true} className={`${plusJakartaFont.variable}`}>
      <body className="flex flex-col scroll-smooth overflow-y-auto">
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  )
}
